<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import AttentionNotice from '../components/AttentionNotice.vue'
import ListFilters from '../components/ListFilters.vue'
import ListPagination from '../components/ListPagination.vue'
import PageHeader from '../components/PageHeader.vue'
import { api } from '../lib/api'
import { toast } from '../lib/toast'
import type { GenerationInput, GenerationModelChoice, GenerationRun, Job, LLMConnection, Profile, Template } from '../lib/types'

const profiles=ref<Profile[]>([]),opportunities=ref<Job[]>([]),templates=ref<Template[]>([]),connections=ref<LLMConnection[]>([]),runs=ref<GenerationRun[]>([])
const models=reactive<Record<string,string[]>>({}),loading=ref(true),submitting=ref(false),deletingId=ref(''),pendingDelete=ref<GenerationRun|null>(null),showCreate=ref(false),error=ref('')
const search=ref(''),stateFilter=ref('all'),page=ref(1),pageSize=ref(8)
const emptyChoice=():GenerationModelChoice=>({connectionId:'',model:''})
const form=reactive<GenerationInput>({profileId:'',opportunityId:'',templateId:'',documentType:'resume',language:'English',pageTarget:'one_page',customInstructions:'',pipelineMode:'single',writer:emptyChoice(),renderer:emptyChoice(),reviewer:emptyChoice()})
let timer:number|undefined
const matchingTemplates=computed(()=>templates.value.filter(item=>item.state==='ready'&&item.kind===form.documentType))
const latexTemplates=computed(()=>matchingTemplates.value.filter(item=>item.format==='latex'))
const ready=computed(()=>Boolean(form.profileId&&form.opportunityId&&form.templateId&&form.writer.connectionId&&form.writer.model&&(form.pipelineMode==='single'||(form.renderer.connectionId&&form.renderer.model&&form.reviewer.connectionId&&form.reviewer.model))))
const active=computed(()=>runs.value.some(item=>item.state==='queued'||item.state==='running'))
const optionName=(values:{id:string;name?:string;title?:string;company?:string}[],id:string)=>{const value=values.find(item=>item.id===id);return value?.name??([value?.title,value?.company].filter(Boolean).join(' · ')||'Deleted input')}
const stageLabel=(run:GenerationRun)=>run.state==='failed'?'Needs attention':({queued:'Waiting',writing:'Writing',rendering:'Applying template',reviewing:'Visual QA',repairing:`Repairing (${run.repairCount}/2)`,finalizing:'Finalizing',ready:'Ready'} as Record<string,string>)[run.stage]??run.stage
const stageProgress=(run:GenerationRun)=>run.state==='failed'?100:({queued:8,writing:20,rendering:42,reviewing:64,repairing:82,finalizing:94,ready:100} as Record<string,number>)[run.stage]??0
const formatDate=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))
const filteredRuns=computed(()=>{const query=search.value.trim().toLocaleLowerCase();return runs.value.filter(run=>{const values=[optionName(opportunities.value,run.opportunityId),optionName(profiles.value,run.profileId),optionName(templates.value,run.templateId),run.writer.model,run.documentType,run.stage];const matchesSearch=!query||values.some(value=>value.toLocaleLowerCase().includes(query));return matchesSearch&&(stateFilter.value==='all'||run.state===stateFilter.value)})})
const visibleRuns=computed(()=>filteredRuns.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value))
watch([search,stateFilter,pageSize],()=>{page.value=1})
watch(()=>filteredRuns.value.length,total=>{page.value=Math.min(page.value,Math.max(1,Math.ceil(total/pageSize.value)))})

async function discover(choice:GenerationModelChoice){if(!choice.connectionId||models[choice.connectionId])return;try{models[choice.connectionId]=(await api.testLLMConnection(choice.connectionId)).models;if(!choice.model)choice.model=models[choice.connectionId][0]??''}catch(cause){error.value=cause instanceof Error?cause.message:'Could not load models.'}}
watch(()=>form.writer.connectionId,()=>discover(form.writer));watch(()=>form.renderer.connectionId,()=>discover(form.renderer));watch(()=>form.reviewer.connectionId,()=>discover(form.reviewer))
watch(()=>form.documentType,()=>{if(!latexTemplates.value.some(item=>item.id===form.templateId))form.templateId=latexTemplates.value[0]?.id??''})
watch(()=>form.pipelineMode,value=>{if(value==='single'){form.renderer={...form.writer};form.reviewer={...form.writer}}})
async function load(){try{const [p,j,t,c,g]=await Promise.all([api.listProfiles(),api.listJobs(),api.listTemplates(),api.listLLMConnections(),api.listGenerations()]);profiles.value=p.items;opportunities.value=j.items;templates.value=t.items;connections.value=c.items;runs.value=g.items;if(!form.profileId)form.profileId=profiles.value[0]?.id??'';if(!form.opportunityId)form.opportunityId=opportunities.value.find(item=>item.description)?.id??'';if(!form.templateId)form.templateId=latexTemplates.value[0]?.id??'';if(!form.writer.connectionId){form.writer.connectionId=connections.value[0]?.id??'';await discover(form.writer)}}catch(cause){error.value=cause instanceof Error?cause.message:'Could not load applications.'}finally{loading.value=false}}
async function refresh(){try{runs.value=(await api.listGenerations()).items}catch{}if(!active.value&&timer){window.clearInterval(timer);timer=undefined}}
async function generate(){error.value='';submitting.value=true;try{const input:GenerationInput=JSON.parse(JSON.stringify(form));if(input.pipelineMode==='single'){input.renderer={...input.writer};input.reviewer={...input.writer}}await api.createGeneration(input);toast.success('Application queued. Open it to follow every stage.');showCreate.value=false;await refresh();if(!timer)timer=window.setInterval(refresh,2000)}catch(cause){error.value=cause instanceof Error?cause.message:'Could not start generation.'}finally{submitting.value=false}}
async function removeGeneration(){const run=pendingDelete.value;if(!run)return;deletingId.value=run.id;error.value='';try{await api.deleteGeneration(run.id);runs.value=runs.value.filter(candidate=>candidate.id!==run.id);pendingDelete.value=null;toast.success('Application deleted.')}catch(cause){error.value=cause instanceof Error?cause.message:'Could not delete the application.'}finally{deletingId.value=''}}
function openCreate(){error.value='';showCreate.value=true}
onMounted(async()=>{await load();if(active.value)timer=window.setInterval(refresh,2000)});onBeforeUnmount(()=>{if(timer)window.clearInterval(timer)})
</script>

<template><div class="page generation-page">
  <PageHeader title="Applications" description="Generate, inspect, and refine tailored application documents from one place."><button class="button primary" type="button" @click="openCreate">＋ New application</button></PageHeader>
  <p v-if="error&&!showCreate" class="notice error">{{ error }}</p>
  <p v-if="!loading&&!connections.length" class="notice setup-notice">No LLM connection is configured. <RouterLink to="/settings">Add one in Settings →</RouterLink></p>
  <div v-if="loading" class="empty-state">Loading applications…</div>
  <section v-else-if="!runs.length" class="empty-state panel"><span class="empty-icon">✦</span><h2>No applications yet</h2><p>Create an application to combine a Profile, Opportunity, and Template into a tracked PDF workflow.</p><button class="button primary" type="button" @click="openCreate">Create first application</button></section>
  <template v-else><ListFilters v-model:search="search" :total="filteredRuns.length" search-placeholder="Search applications, profiles, templates, or models…"><label>Status <select v-model="stateFilter"><option value="all">All statuses</option><option value="queued">Queued</option><option value="running">Running</option><option value="ready">Ready</option><option value="failed">Needs attention</option></select></label></ListFilters>
  <TransitionGroup v-if="visibleRuns.length" name="card-list" tag="section" class="application-grid"><article v-for="run in visibleRuns" :key="run.id" class="panel application-card">
    <header><div><span class="document-kind">{{ run.documentType==='resume'?'Resume':'Cover letter' }}</span><h2>{{ optionName(opportunities,run.opportunityId) }}</h2><p>{{ optionName(profiles,run.profileId) }} · {{ optionName(templates,run.templateId) }}</p></div><span class="status-pill" :class="run.state">{{ stageLabel(run) }}</span></header>
    <div class="progress-track"><span :class="run.state" :style="{width:`${stageProgress(run)}%`}" /></div>
    <div class="application-meta"><span>{{ run.pageTarget.replace('_',' ') }}</span><span>{{ run.pipelineMode==='single'?'Single model':'Specialized models' }}</span><span>{{ formatDate(run.createdAt) }}</span></div>
    <AttentionNotice v-if="run.state==='failed'" compact :message="run.errorMessage||'Generation stopped before completion. Open the application to retry or review its inputs and model connection.'" :code="run.errorCode"/><p v-else-if="run.review?.startsWith('Template fallback used:')||run.review?.startsWith('Visual QA skipped:')" class="card-message warning-text">Completed with workflow warnings. Open the application for details.</p>
    <footer><span>{{ run.writer.model }}</span><div class="card-actions"><button class="text-button danger-text" type="button" @click="pendingDelete=run">Delete</button><RouterLink v-if="run.state!=='queued'&&run.state!=='running'" class="text-button" :to="{path:`/generate/${run.id}`,query:{edit:'1'}}">Edit</RouterLink><RouterLink class="button" :to="`/generate/${run.id}`">View</RouterLink></div></footer>
  </article></TransitionGroup><div v-else class="empty-state compact"><h2>No matching applications</h2><p>Try another keyword or status.</p></div><ListPagination v-if="filteredRuns.length" v-model:page="page" v-model:page-size="pageSize" :total="filteredRuns.length" /></template>

  <div v-if="showCreate" class="modal-backdrop" @click.self="showCreate=false"><section class="panel generation-modal" role="dialog" aria-modal="true" aria-labelledby="new-application-title">
    <header class="modal-header"><div><p class="eyebrow">New application</p><h2 id="new-application-title">Configure generation</h2></div><button class="modal-close" type="button" aria-label="Close" @click="showCreate=false">×</button></header>
    <p v-if="error" class="notice error">{{ error }}</p>
    <form @submit.prevent="generate"><div class="form-grid">
      <label><span>Document type</span><select v-model="form.documentType"><option value="resume">Resume</option><option value="cover_letter">Cover letter</option></select></label><label><span>Output language</span><input v-model="form.language" required maxlength="40" /></label>
      <label><span>Profile</span><select v-model="form.profileId" required><option value="" disabled>Select a profile</option><option v-for="item in profiles" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Opportunity</span><select v-model="form.opportunityId" required><option value="" disabled>Select an opportunity</option><option v-for="item in opportunities" :key="item.id" :value="item.id">{{ item.title }} · {{ item.company }}</option></select></label>
      <label><span>LaTeX template</span><select v-model="form.templateId" required><option value="" disabled>Select a template</option><option v-for="item in latexTemplates" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Page target</span><select v-model="form.pageTarget"><option value="one_page">One page</option><option value="two_pages">Two pages</option><option value="flexible">Flexible</option></select></label>
      <label class="full"><span>Custom instructions</span><textarea v-model="form.customInstructions" rows="3" maxlength="4000" placeholder="Optional emphasis or tone for this application." /></label>
      <div class="full pipeline-choice"><label><input v-model="form.pipelineMode" type="radio" value="single" /> One model</label><label><input v-model="form.pipelineMode" type="radio" value="multi" /> Specialized models</label></div>
      <fieldset class="full model-card"><legend>{{ form.pipelineMode==='single'?'Workflow model':'Writer model' }}</legend><div class="model-row"><label><span>Connection</span><select v-model="form.writer.connectionId"><option value="" disabled>Select connection</option><option v-for="item in connections" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Model</span><input v-model="form.writer.model" :list="`models-${form.writer.connectionId}`" placeholder="Model name" /><datalist :id="`models-${form.writer.connectionId}`"><option v-for="model in models[form.writer.connectionId]||[]" :key="model" :value="model" /></datalist></label></div><small v-if="form.pipelineMode==='single'">A text-only model can still generate a PDF; visual QA will be skipped with a warning.</small></fieldset>
      <template v-if="form.pipelineMode==='multi'"><fieldset class="full model-card"><legend>Template applier</legend><div class="model-row"><label><span>Connection</span><select v-model="form.renderer.connectionId"><option value="" disabled>Select connection</option><option v-for="item in connections" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Model</span><input v-model="form.renderer.model" :list="`models-${form.renderer.connectionId}`" /></label></div></fieldset><fieldset class="full model-card"><legend>Visual reviewer</legend><div class="model-row"><label><span>Connection</span><select v-model="form.reviewer.connectionId"><option value="" disabled>Select connection</option><option v-for="item in connections" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Model</span><input v-model="form.reviewer.model" :list="`models-${form.reviewer.connectionId}`" /></label></div></fieldset></template>
    </div><div class="modal-actions"><button class="button" type="button" @click="showCreate=false">Cancel</button><button class="button primary" :disabled="!ready||submitting">{{ submitting?'Queuing…':'Create application' }}</button></div></form>
  </section></div>
  <ConfirmDialog :open="Boolean(pendingDelete)" title="Delete application?" :message="`The application for “${pendingDelete ? optionName(opportunities, pendingDelete.opportunityId) : ''}” and its generation history will be removed. This action cannot be undone.`" :busy="deletingId===pendingDelete?.id" @cancel="pendingDelete=null" @confirm="removeGeneration" />
</div></template>
