<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import AttentionNotice from '../components/AttentionNotice.vue'
import ListFilters from '../components/ListFilters.vue'
import ListPagination from '../components/ListPagination.vue'
import PageHeader from '../components/PageHeader.vue'
import { api } from '../lib/api'
import { toast } from '../lib/toast'
import type { AgentDefault, GenerationInput, GenerationModelChoice, GenerationRun, Job, LLMConnection, Profile, Template } from '../lib/types'

const profiles=ref<Profile[]>([]),opportunities=ref<Job[]>([]),templates=ref<Template[]>([]),connections=ref<LLMConnection[]>([]),runs=ref<GenerationRun[]>([])
const models=reactive<Record<string,string[]>>({}),loading=ref(true),submitting=ref(false),deletingId=ref(''),pendingDelete=ref<GenerationRun|null>(null),showCreate=ref(false),error=ref(''),useSpecifiedModel=ref(false)
const loadingModelConnections=reactive<Record<string,boolean>>({})
const search=ref(''),stateFilter=ref('all'),page=ref(1),pageSize=ref(8)
const emptyChoice=():GenerationModelChoice=>({connectionId:'',model:''})
const form=reactive<GenerationInput>({profileId:'',opportunityId:'',templateId:'',documentType:'resume',language:'English',pageTarget:'one_page',customInstructions:'',pipelineMode:'multi',writer:emptyChoice(),renderer:emptyChoice(),reviewer:emptyChoice()})
const writerDefault=ref<GenerationModelChoice|null>(null),templateApplierDefault=ref<GenerationModelChoice|null>(null),designerDefault=ref<GenerationModelChoice|null>(null),reviewerDefault=ref<GenerationModelChoice|null>(null)
let timer:number|undefined
const matchingTemplates=computed(()=>templates.value.filter(item=>item.state==='ready'&&item.kind===form.documentType))
const latexTemplates=computed(()=>matchingTemplates.value.filter(item=>item.format==='latex'))
const ready=computed(()=>Boolean(form.profileId&&form.opportunityId&&form.writer.connectionId&&form.writer.model&&(form.pipelineMode==='single'||(form.renderer.connectionId&&form.renderer.model&&form.reviewer.connectionId&&form.reviewer.model))))
const active=computed(()=>runs.value.some(item=>item.state==='queued'||item.state==='running'))
const optionName=(values:{id:string;name?:string;title?:string;company?:string}[],id:string)=>{const value=values.find(item=>item.id===id);return value?.name??([value?.title,value?.company].filter(Boolean).join(' · ')||'Deleted input')}
const stageLabel=(run:GenerationRun)=>run.state==='failed'?'Needs attention':({queued:'Waiting',writing:'Writing',rendering:run.templateId?'Applying template':'Designing document',reviewing:'Visual QA',repairing:`Repairing (${run.repairCount}/2)`,finalizing:'Finalizing',ready:'Ready'} as Record<string,string>)[run.stage]??run.stage
const stageProgress=(run:GenerationRun)=>run.state==='failed'?100:({queued:8,writing:20,rendering:42,reviewing:64,repairing:82,finalizing:94,ready:100} as Record<string,number>)[run.stage]??0
const formatDate=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))
const filteredRuns=computed(()=>{const query=search.value.trim().toLocaleLowerCase();return runs.value.filter(run=>{const values=[optionName(opportunities.value,run.opportunityId),optionName(profiles.value,run.profileId),optionName(templates.value,run.templateId),run.writer.model,run.documentType,run.stage];const matchesSearch=!query||values.some(value=>value.toLocaleLowerCase().includes(query));return matchesSearch&&(stateFilter.value==='all'||run.state===stateFilter.value)})})
const templateName=(id:string)=>id?optionName(templates.value,id):'Designed without a template'
const visibleRuns=computed(()=>filteredRuns.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value))
watch([search,stateFilter,pageSize],()=>{page.value=1})
watch(()=>filteredRuns.value.length,total=>{page.value=Math.min(page.value,Math.max(1,Math.ceil(total/pageSize.value)))})

async function discover(choice:GenerationModelChoice){const connectionId=choice.connectionId;if(!connectionId)return;if(models[connectionId]){if(!choice.model)choice.model=models[connectionId][0]??'';return}loadingModelConnections[connectionId]=true;try{models[connectionId]=(await api.testLLMConnection(connectionId)).models;if(choice.connectionId===connectionId&&!choice.model)choice.model=models[connectionId][0]??''}catch(cause){error.value=cause instanceof Error?cause.message:'Could not load models.'}finally{loadingModelConnections[connectionId]=false}}
function changeConnection(choice:GenerationModelChoice){choice.model='';void discover(choice)}
watch(()=>form.documentType,()=>{if(form.templateId&&!latexTemplates.value.some(item=>item.id===form.templateId))form.templateId=''})
watch(()=>form.templateId,()=>{if(!useSpecifiedModel.value){const choice=form.templateId?templateApplierDefault.value:designerDefault.value;if(choice)form.renderer={...choice};void discover(form.renderer)}})
watch(useSpecifiedModel,value=>{form.pipelineMode=value?'single':'multi';if(value){form.renderer={...form.writer};form.reviewer={...form.writer}}else{form.writer={...(writerDefault.value??form.writer)};form.renderer={...((form.templateId?templateApplierDefault.value:designerDefault.value)??form.writer)};form.reviewer={...(reviewerDefault.value??form.writer)};void Promise.all([discover(form.writer),discover(form.renderer),discover(form.reviewer)])}})
async function load(){try{const [p,j,t,c,g,d]=await Promise.all([api.listProfiles(),api.listJobs(),api.listTemplates(),api.listLLMConnections(),api.listGenerations(),api.getAgentDefaults()]);profiles.value=p.items;opportunities.value=j.items;templates.value=t.items;connections.value=c.items;runs.value=g.items;if(!form.profileId)form.profileId=profiles.value[0]?.id??'';if(!form.opportunityId)form.opportunityId=opportunities.value.find(item=>item.hasDescription)?.id??'';const defaults=Object.fromEntries(d.items.map((item:AgentDefault)=>[item.agent,item]));const valid=(choice?:AgentDefault)=>choice&&connections.value.some(item=>item.id===choice.connectionId)?{connectionId:choice.connectionId,model:choice.model}:undefined;const fallback=valid(defaults.writer)??{connectionId:connections.value[0]?.id??'',model:''};writerDefault.value={...fallback};templateApplierDefault.value=valid(defaults.template_applier)??{...fallback};designerDefault.value=valid(defaults.document_designer)??{...fallback};reviewerDefault.value=valid(defaults.visual_reviewer)??{...fallback};useSpecifiedModel.value=false;form.pipelineMode='multi';form.writer={...fallback};form.renderer={...(designerDefault.value??fallback)};form.reviewer={...(reviewerDefault.value??fallback)};await Promise.all([discover(form.writer),discover(form.renderer),discover(form.reviewer)])}catch(cause){error.value=cause instanceof Error?cause.message:'Could not load generated documents.'}finally{loading.value=false}}
async function refresh(){try{runs.value=(await api.listGenerations()).items}catch{}if(!active.value&&timer){window.clearInterval(timer);timer=undefined}}
async function generate(){error.value='';submitting.value=true;try{const input:GenerationInput=JSON.parse(JSON.stringify(form));if(input.pipelineMode==='single'){input.renderer={...input.writer};input.reviewer={...input.writer}}await api.createGeneration(input);toast.success('Generation queued. Open it to follow every stage.');showCreate.value=false;await refresh();if(!timer)timer=window.setInterval(refresh,2000)}catch(cause){error.value=cause instanceof Error?cause.message:'Could not start generation.'}finally{submitting.value=false}}
async function removeGeneration(){const run=pendingDelete.value;if(!run)return;deletingId.value=run.id;error.value='';try{await api.deleteGeneration(run.id);runs.value=runs.value.filter(candidate=>candidate.id!==run.id);pendingDelete.value=null;toast.success('Generated document deleted.')}catch(cause){error.value=cause instanceof Error?cause.message:'Could not delete the generated document.'}finally{deletingId.value=''}}
function openCreate(){error.value='';useSpecifiedModel.value=false;form.pipelineMode='multi';form.writer={...(writerDefault.value??form.writer)};form.renderer={...((form.templateId?templateApplierDefault.value:designerDefault.value)??form.writer)};form.reviewer={...(reviewerDefault.value??form.writer)};void Promise.all([discover(form.writer),discover(form.renderer),discover(form.reviewer)]);showCreate.value=true}
onMounted(async()=>{await load();if(active.value)timer=window.setInterval(refresh,2000)});onBeforeUnmount(()=>{if(timer)window.clearInterval(timer)})
</script>

<template><div class="page generation-page">
  <PageHeader title="Create CVs and Cover Letters" description="Create a tailored CV or cover letter for each job opportunity, then review and refine every result."><button class="button primary" type="button" @click="openCreate">＋ Create CV or Cover Letter</button></PageHeader>
  <p v-if="error&&!showCreate" class="notice error">{{ error }}</p>
  <p v-if="!loading&&!connections.length" class="notice setup-notice">No LLM provider is configured. <RouterLink to="/settings">Add one in Settings →</RouterLink></p>
  <div v-if="loading" class="empty-state">Loading generated documents…</div>
  <section v-else-if="!runs.length" class="empty-state panel"><span class="empty-icon">✦</span><h2>No CVs or cover letters yet</h2><p>Combine a Profile, Job Opportunity, and optional Template into a tailored, tracked PDF workflow.</p><button class="button primary" type="button" @click="openCreate">Create your first CV or Cover Letter</button></section>
  <template v-else><ListFilters v-model:search="search" :total="filteredRuns.length" search-placeholder="Search CVs, cover letters, profiles, templates, or models…"><label>Status <select v-model="stateFilter"><option value="all">All statuses</option><option value="queued">Queued</option><option value="running">Running</option><option value="ready">Ready</option><option value="failed">Needs attention</option></select></label></ListFilters>
  <TransitionGroup v-if="visibleRuns.length" name="card-list" tag="section" class="application-grid"><article v-for="run in visibleRuns" :key="run.id" class="panel application-card">
    <header><div><span class="document-kind">{{ run.documentType==='resume'?'Résumé':'Cover letter' }}</span><h2>{{ optionName(opportunities,run.opportunityId) }}</h2><p>{{ optionName(profiles,run.profileId) }} · {{ templateName(run.templateId) }}</p></div><span class="status-pill" :class="run.state">{{ stageLabel(run) }}</span></header>
    <div class="progress-track"><span :class="run.state" :style="{width:`${stageProgress(run)}%`}" /></div>
    <div class="application-meta"><span>{{ run.pageTarget.replace('_',' ') }}</span><span>{{ run.pipelineMode==='single'?'Single model':'Specialized models' }}</span><span>{{ formatDate(run.createdAt) }}</span></div>
    <AttentionNotice v-if="run.state==='failed'" compact :message="run.errorMessage||'Generation stopped before completion. Open it to retry or review its inputs and model provider.'" :code="run.errorCode"/><p v-else-if="run.hasWarning" class="card-message warning-text">Completed with workflow warnings. Open the generated document for details.</p>
    <footer><span>{{ run.writer.model }}</span><div class="card-actions"><button class="text-button danger-text" type="button" @click="pendingDelete=run">Delete</button><RouterLink v-if="run.state!=='queued'&&run.state!=='running'" class="text-button" :to="{path:`/generate/${run.id}`,query:{edit:'1'}}">Edit</RouterLink><RouterLink class="button" :to="`/generate/${run.id}`">View</RouterLink></div></footer>
  </article></TransitionGroup><div v-else class="empty-state compact"><h2>No matching CVs or cover letters</h2><p>Try another keyword or status.</p></div><ListPagination v-if="filteredRuns.length" v-model:page="page" v-model:page-size="pageSize" :total="filteredRuns.length" /></template>

  <div v-if="showCreate" class="modal-backdrop" @click.self="showCreate=false"><section class="panel generation-modal" role="dialog" aria-modal="true" aria-labelledby="new-generation-title">
    <header class="modal-header"><div><p class="eyebrow">Create CV or Cover Letter</p><h2 id="new-generation-title">Configure generation</h2></div><button class="modal-close" type="button" aria-label="Close" @click="showCreate=false">×</button></header>
    <p v-if="error" class="notice error">{{ error }}</p>
    <form @submit.prevent="generate"><div class="form-grid">
      <label><span>Document type</span><select v-model="form.documentType"><option value="resume">Résumé</option><option value="cover_letter">Cover letter</option></select></label><label><span>Output language</span><input v-model="form.language" required maxlength="40" /></label>
      <label><span>Profile</span><select v-model="form.profileId" required><option value="" disabled>Select a profile</option><option v-for="item in profiles" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Job opportunity</span><select v-model="form.opportunityId" required><option value="" disabled>Select a job opportunity</option><option v-for="item in opportunities" :key="item.id" :value="item.id">{{ item.title }} · {{ item.company }}</option></select></label>
      <label><span>Template</span><select v-model="form.templateId"><option value="">No template — let AI design it</option><option v-for="item in latexTemplates" :key="item.id" :value="item.id">{{ item.name }}</option></select><small v-if="!form.templateId">The Document Designer will create a print-ready HTML/CSS layout.</small></label><label><span>Page target</span><select v-model="form.pageTarget"><option value="one_page">One page</option><option value="two_pages">Two pages</option><option value="flexible">Flexible</option></select></label>
      <label class="full"><span>Custom instructions</span><textarea v-model="form.customInstructions" rows="3" maxlength="4000" placeholder="Optional emphasis or tone for this document." /></label>
      <div class="full model-routing"><label class="model-switch"><input v-model="useSpecifiedModel" type="checkbox" role="switch" /><span class="model-switch-track" aria-hidden="true"><span /></span><span>Use a specific model</span></label><p v-if="!useSpecifiedModel">Each agent uses its default model from System Settings. <RouterLink to="/settings">Configure agent models →</RouterLink></p><p v-else>The selected model will handle writing, document creation, and visual review for this CV or cover letter.</p></div>
      <fieldset v-if="useSpecifiedModel" class="full model-card"><legend>Model for every agent</legend><div class="model-row"><label><span>Provider</span><select v-model="form.writer.connectionId" @change="changeConnection(form.writer)"><option value="" disabled>Select provider</option><option v-for="item in connections" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>Model</span><select v-if="models[form.writer.connectionId]?.length" v-model="form.writer.model" required><option value="" disabled>Select model</option><option v-for="model in models[form.writer.connectionId]" :key="model" :value="model">{{ model }}</option></select><input v-else v-model="form.writer.model" required :disabled="loadingModelConnections[form.writer.connectionId]" :placeholder="loadingModelConnections[form.writer.connectionId]?'Loading models…':'Enter model name'" /></label></div><small>A text-only model can still generate a PDF; visual QA will be skipped with a warning.</small></fieldset>
    </div><div class="modal-actions"><button class="button" type="button" @click="showCreate=false">Cancel</button><button class="button primary" :disabled="!ready||submitting">{{ submitting?'Queuing…':'Create CV or Cover Letter' }}</button></div></form>
  </section></div>
  <ConfirmDialog :open="Boolean(pendingDelete)" title="Delete generated document?" :message="`The generated document for “${pendingDelete ? optionName(opportunities, pendingDelete.opportunityId) : ''}” and its history will be removed. This action cannot be undone.`" :busy="deletingId===pendingDelete?.id" @cancel="pendingDelete=null" @confirm="removeGeneration" />
</div></template>
